SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE movies;
TRUNCATE TABLE rooms;
TRUNCATE TABLE room_rows;
TRUNCATE TABLE screenings;
TRUNCATE TABLE seats;
TRUNCATE TABLE tickets;
SET REFERENTIAL_INTEGRITY TRUE;



